trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# Use Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

# Install dependencies including ODBC driver
- script: |
    sudo apt-get update
    sudo apt-get install -y unixodbc-dev msodbcsql18
    pip install pandas sqlalchemy pyodbc
  displayName: 'Install dependencies and ODBC driver'

# Check driver
- script: |
    python -c "import pyodbc; print(pyodbc.drivers())"
  displayName: 'Check available ODBC drivers'


# Run your data load script
- script: |
    python load_data.py
  displayName: 'Load CSV data into Azure SQL'
  env:
    SQL_PASSWORD: $(SQL_PASSWORD)
